name: 'RecoveryServices - Vaults'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.recoveryservices.vaults.yml'
      - '/.azuredevops/pipelineTemplates/module.*.yml'
      - '/arm/Microsoft.RecoveryServices/vaults/*'
      - '/arm/.global/global.module.tests.ps1'
    exclude:
      - '/**/*.md'

variables:
  - template: '../../global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/arm/Microsoft.RecoveryServices/vaults'

stages:
  - stage: Validation
    displayName: Static validation
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModulePester.yml

  - stage: Deployment
    displayName: Deployment validation
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
        parameters:
          removeDeployment: '${{ parameters.removeDeployment }}'
          deploymentBlocks:
            - path: $(modulePath)/.parameters/parameters.json
              templateFilePath: $(modulePath)/deploy.bicep
            - path: $(modulePath)/.parameters/min.parameters.json
              templateFilePath: $(modulePath)/deploy.bicep
            - path: $(modulePath)/.parameters/dr.parameters.json
              templateFilePath: $(modulePath)/deploy.bicep
            - path: $(modulePath)/.parameters/encr.parameters.json
              templateFilePath: $(modulePath)/deploy.bicep

  - stage: Publishing
    displayName: Publishing
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('${{ parameters.prerelease }}', 'true')))
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.publishModule.yml
